services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    expose:
      - 25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "8192M"
      USE_AIKAR_FLAGS: "true"
      VIEW_DISTANCE: "12"
    volumes:
      - data:/data
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.mc.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.mc.entrypoints=mc
      - traefik.http.services.mc.loadbalancer.server.port=25565
volumes:
  data:
